#!/usr/bin/env bash
set -euo pipefail

source "$(dirname "$0")/common.sh"
ROOT="$PF_ROOT"
cd "$ROOT"

usage() {
  cat <<'USAGE'
Usage:
  ./scripts/review_assets.sh [asset-stem ...]

Builds actionable review.html + review.txt reports from complete analysis diagnostics or,
when analysis failed, the newest compact diagnostics retained under /tmp. Includes verification/render
provenance when available and writes a browsable index to output/review/index.html.
USAGE
}

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  usage
  exit 0
fi

pf_build_release

if (( $# )); then
  cases=("$@")
else
  pf_asset_cases cases
fi

mkdir -p output/review
index_tmp="output/review/.index.html.tmp"
cat > "$index_tmp" <<'HTML'
<!doctype html><html><head><meta charset="utf-8"><title>Plaque Forge quality reports</title>
<style>body{font:16px system-ui,sans-serif;max-width:1000px;margin:2rem auto;padding:0 1rem;background:#111;color:#ddd}a{color:#77e8ff}li{margin:.6rem 0}.ok{color:#8fda8f}.partial{color:#ffd27a}code{color:#fff}</style></head><body>
<h1>Plaque Forge quality reports</h1>
<p>Open an asset report for prioritized findings, visual evidence, exact scene guidance, and render/verification provenance.</p><ul>
HTML

reports=0
for name in "${cases[@]}"; do
  analysis="assets/analysis/$name"
  status="complete"
  if [[ ! -d "$analysis" ]]; then
    analysis="$(ls -1dt "/tmp/plaque-forge/failures/$name/"* 2>/dev/null | head -n 1 || true)"
    status="partial"
  fi
  if [[ -z "$analysis" || ! -d "$analysis" ]]; then
    printf 'warning: no complete or retained failure diagnostics found for %s\n' "$name" >&2
    printf '<li><code>%s</code>: no analysis available</li>\n' "$name" >> "$index_tmp"
    continue
  fi

  verification="output/validation/$name.lossless.verification.json"
  render_manifest="output/validation/$name.lossless.render-manifest.json"
  [[ -f "$verification" ]] || verification=""
  [[ -f "$render_manifest" ]] || render_manifest=""
  # Verification is never shown without its retained lossless render manifest.
  if [[ -n "$verification" && -z "$render_manifest" ]]; then
    verification=""
  fi
  # A delivery render still carries useful provenance-bound causal diagnostics even
  # when no exhaustive lossless verification has been run yet.
  if [[ -z "$render_manifest" && -f "output/$name.hevc.render-manifest.json" ]]; then
    render_manifest="output/$name.hevc.render-manifest.json"
  fi
  scene="assets/scenes/$name/scene.toml"
  args=(--analysis "$analysis")
  [[ -f "$scene" ]] && args+=(--scene "$scene")
  [[ -n "$verification" ]] && args+=(--verification "$verification")
  [[ -n "$render_manifest" ]] && args+=(--render-manifest "$render_manifest")
  target/release/plaque-forge review "${args[@]}"

  report="$analysis/diagnostics/review.html"
  if [[ -f "$report" ]]; then
    relative="$(realpath --relative-to=output/review "$report")"
    css_class="ok"
    label="complete"
    if [[ "$status" == "partial" ]]; then css_class="partial"; label="needs attention"; fi
    printf '<li><a href="%s"><code>%s</code></a> <span class="%s">%s</span></li>\n' \
      "$relative" "$name" "$css_class" "$label" >> "$index_tmp"
    reports=$((reports + 1))
  fi
done

cat >> "$index_tmp" <<'HTML'
</ul><p>Generated by <code>./scripts/review_assets.sh</code>. Reports are regenerated from existing analysis and output metadata; this command does not rerun expensive scene analysis.</p></body></html>
HTML
mv -f -- "$index_tmp" output/review/index.html
printf '\nquality report index: output/review/index.html (%d report(s))\n' "$reports"
